version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka1"
      KAFKA_BROKER_ID: 1
      
  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9094:9094"
    expose:
      - "9095"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9095,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka2"
      KAFKA_BROKER_ID: 2

  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9096:9096"
    expose:
      - "9097"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9097,OUTSIDE://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9097,OUTSIDE://0.0.0.0:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka3"
      KAFKA_BROKER_ID: 3

  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  kafka-consumer:
    build: 
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka1
      - kafka2
      - kafka3