version: '3'
services:
  cassandra-node1:
    container_name: cassandra-node1
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=cassandraCluster
    networks:
      - cassandra-net

  cassandra-node2:
    container_name: cassandra-node2
    image: cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=cassandraCluster
    networks:
      - cassandra-net
        
networks:
  cassandra-net:
    driver: bridge
